In [227]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [228]:
x = np.ones([1, 5])
x

array([[1., 1., 1., 1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [229]:
y = np.zeros([1, 5])
y

array([[0., 0., 0., 0., 0.]])

## Q#3: Add x and y arrays.

In [230]:
sum_arrays = x + y
sum_arrays

array([[1., 1., 1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

In [231]:
print(x.ndim)
print(x.dtype)
print(x.shape)
print(x.size)

2
float64
(1, 5)
5


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [232]:
w = np.array([[11, 12],[13, 14],[15, 16]])
w 

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [233]:
z = np.arange(1, 4)
z 

array([1, 2, 3])

## Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".

In [234]:
newArray = np.column_stack((z, w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [235]:
for i in newArray:
    for j in i:
        print(j)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [236]:
newArray.transpose()

array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [237]:
newArray = newArray - 1
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [238]:
print(newArray.max())
print(newArray.min())

15
0


## Q#12: Print the first row of "newArray" using indexing.

In [239]:
print(newArray[0])

[ 0 10 11]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [240]:
print(newArray[1, 1])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

In [241]:
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

In [242]:
print(newArray[:2, 0:1])

[[0]
 [1]]


## Q#15: Change the shape of "newArray" to (9,1).

In [243]:
newArray = newArray.reshape(9, 1)
newArray

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [244]:
# ERROR

# Well Done 🎉