# Q1: Import numpy library

In [1]:
# write your code here ^_^
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [2]:
# write your code here ^_^
np.linspace(0, 2, 15) 

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [3]:
# write your code here ^_^
my_3d_array = np.array([[[1.1, 2.1, 3.1], [4.1, 5.1, 6.1]], [[7.1, 8.1, 9.1], [10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [4]:
# write your code here ^_^
print(type(my_3d_array))
print(my_3d_array.dtype)
print(my_3d_array.shape)
print(my_3d_array.ndim)
print(my_3d_array.size)

<class 'numpy.ndarray'>
float64
(2, 2, 3)
3
12


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [5]:
# write your code here ^_^
my_4d_array = np.array(my_3d_array, ndmin=4)
print(my_4d_array.ndim)
print(my_4d_array.shape)

4
(1, 2, 2, 3)


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [6]:
# write your code here ^_^
my_new_array = my_4d_array.astype(int)
print(my_new_array)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [7]:
# write your code here ^_^
for x in np.nditer(my_new_array):
    print(x, end= ' ')

1 2 3 4 5 6 7 8 9 10 11 12 

# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [8]:
# write your code here ^_^
print(my_new_array[0, 1, 0, 1])

8


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [9]:
# write your code here ^_^
print(my_new_array[0, 0, 1, 1:])

[5 6]


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [10]:
# write your code here ^_^
print(np.where(my_new_array == 8))

(array([0]), array([1]), array([0]), array([1]))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [11]:
# write your code here ^_^
my_new_array.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [12]:
# write your code here ^_^
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

joined_arrays = np.concatenate((arr1, arr2))
print(joined_arrays)

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [13]:
# write your code here ^_^
joined_arrays2 = np.concatenate((arr1, arr2), axis = 1)
print(joined_arrays2)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [14]:
# write your code here ^_^
split_joined_arrays = np.array_split(joined_arrays, 2, axis = 1)
print(split_joined_arrays)

[array([['A'],
       ['E'],
       ['C'],
       ['G']], dtype='<U1'), array([['B'],
       ['F'],
       ['D'],
       ['H']], dtype='<U1')]
