# Q1: Import numpy library

In [1]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [5]:
np.linspace(1, 30, num=15, dtype=float, axis=0)

array([ 1.        ,  3.07142857,  5.14285714,  7.21428571,  9.28571429,
       11.35714286, 13.42857143, 15.5       , 17.57142857, 19.64285714,
       21.71428571, 23.78571429, 25.85714286, 27.92857143, 30.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [57]:
lst1=[1.1, 2.1, 3.1]
lst2=[4.1, 5.1, 6.1]
lst3=[7.1, 8.1, 9.1]
lst4=[10.1, 11.1, 12.1]


arr = np.array([[lst1, lst2], [lst3, lst4]])
arr



array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [12]:
print(arr.shape)
print(arr.dtype)
print(arr.size)
print(arr.ndim)

(2, 2, 3)
float64
12
3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [59]:
newarr = arr.reshape((1, 2, 2, 3))
newarr

array([[[[ 1.1,  2.1,  3.1],
         [ 4.1,  5.1,  6.1]],

        [[ 7.1,  8.1,  9.1],
         [10.1, 11.1, 12.1]]]])

# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [121]:
newarr2= arr.astype('int')
newarr2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [63]:
for row in newarr2:
    for row2 in row:
        for item in row2:
            print(item)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [105]:
print(newarr2[1:,0:1,1:-1])

[[[8]]]


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [114]:
print(newarr2[0:1,1:2,1:-1])

[[[5]]]


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [117]:
x = np.where(newarr2 == 8)

print(x)
print(newarr2)


(array([1]), array([0]), array([1]))
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [128]:

newarr2 = newarr2.reshape((1, 2, 3, 2))
newarr2

array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [133]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
print(np.hstack((arr1,arr2)))

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [135]:
newarr3=np.vstack((arr1,arr2))
print(newarr3)

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [137]:
[B,C] = np.hsplit(newarr3, 2)
print(B)
print(C)

[['A']
 ['E']
 ['C']
 ['G']]
[['B']
 ['F']
 ['D']
 ['H']]
