# Q1: Import numpy library

In [19]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [20]:
np.linspace(start = 0.0, stop = 1, num = 15)

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [26]:
Three_D = np.array([[1.1,2.1,3.1],[4.1,5.1,6.1],[7.1,8.1,9.1],[10.1,11.1,12.1]])
print(Three_D)
Three_DD = Three_D.reshape(2,2,3)
Three_D.shape
Three_DD.shape
print(Three_DD)

[[ 1.1  2.1  3.1]
 [ 4.1  5.1  6.1]
 [ 7.1  8.1  9.1]
 [10.1 11.1 12.1]]
[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [22]:
Three_DD.dtype
Three_DD.shape
Three_DD.size
Three_DD.ndim

3

In [23]:
print(Three_DD.data)

# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [47]:
x = np.random.randn(4, 3, 3, 2)
print(x)


[[[[-0.89016644  0.33972603]
   [-0.2954494   0.21979414]
   [-2.1920798   0.29882369]]

  [[-1.0369276  -0.29562669]
   [-0.42704447 -0.08594202]
   [-0.86525613 -1.71161478]]

  [[ 0.31828061 -0.32557681]
   [ 0.11443428  2.44071687]
   [ 2.10969251 -0.64861667]]]


 [[[-0.24560222 -1.43749259]
   [ 0.51687361 -1.49798289]
   [-0.62566476  0.77511548]]

  [[ 1.27573122  0.90627733]
   [-0.56243218 -1.10282994]
   [ 0.05315345 -1.32236359]]

  [[ 0.31293013  1.44363316]
   [-0.67078154 -0.1937849 ]
   [ 1.05212144  0.46888678]]]


 [[[ 0.99717355 -0.99796031]
   [ 0.2404431  -0.10028465]
   [ 0.06270752 -0.92079155]]

  [[ 1.84655501  0.48951764]
   [-0.98302611  0.22896668]
   [ 0.53551554 -2.45202564]]

  [[-0.63409814 -1.86799508]
   [-0.74611735 -1.40537558]
   [-0.03668328  0.64182958]]]


 [[[-0.2243092  -0.0143621 ]
   [-0.4425247  -0.27664447]
   [-0.92820614 -0.41252172]]

  [[-1.64177552  0.27936152]
   [-0.2043775   0.08454316]
   [ 0.16181626 -1.81156877]]

  [[ 1.27320252

# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [48]:
y = rounded_down_integer_array = x.astype(int)
print(y)

[[[[ 0  0]
   [ 0  0]
   [-2  0]]

  [[-1  0]
   [ 0  0]
   [ 0 -1]]

  [[ 0  0]
   [ 0  2]
   [ 2  0]]]


 [[[ 0 -1]
   [ 0 -1]
   [ 0  0]]

  [[ 1  0]
   [ 0 -1]
   [ 0 -1]]

  [[ 0  1]
   [ 0  0]
   [ 1  0]]]


 [[[ 0  0]
   [ 0  0]
   [ 0  0]]

  [[ 1  0]
   [ 0  0]
   [ 0 -2]]

  [[ 0 -1]
   [ 0 -1]
   [ 0  0]]]


 [[[ 0  0]
   [ 0  0]
   [ 0  0]]

  [[-1  0]
   [ 0  0]
   [ 0 -1]]

  [[ 1  0]
   [ 1  0]
   [ 1  0]]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [49]:
for cell in np.nditer(y):
    print(cell, end=' ')

0 0 0 0 -2 0 -1 0 0 0 0 -1 0 0 0 2 2 0 0 -1 0 -1 0 0 1 0 0 -1 0 -1 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 -2 0 -1 0 -1 0 0 0 0 0 0 0 0 -1 0 0 0 0 -1 1 0 1 0 1 0 

# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [55]:
print(y[2,2,2,1])

0


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [ ]:
# write your code here ^_^

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [65]:

b = np.where(y == 2 )
print(b)

(array([0, 0], dtype=int64), array([2, 2], dtype=int64), array([1, 2], dtype=int64), array([1, 0], dtype=int64))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [69]:
reshape = y.reshape(6,3,4)
print(reshape)

[[[ 0  0  0  0]
  [-2  0 -1  0]
  [ 0  0  0 -1]]

 [[ 0  0  0  2]
  [ 2  0  0 -1]
  [ 0 -1  0  0]]

 [[ 1  0  0 -1]
  [ 0 -1  0  1]
  [ 0  0  1  0]]

 [[ 0  0  0  0]
  [ 0  0  1  0]
  [ 0  0  0 -2]]

 [[ 0 -1  0 -1]
  [ 0  0  0  0]
  [ 0  0  0  0]]

 [[-1  0  0  0]
  [ 0 -1  1  0]
  [ 1  0  1  0]]]


# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [70]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
arra3 = np.concatenate((arr1, arr2), axis=0)
print(arra3)

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [71]:
arra4 = np.concatenate((arr1, arr2), axis=1)
print(arra4)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [74]:
print(np.split(arra4, 2, axis=1))


[array([['A', 'B'],
       ['E', 'F']], dtype='<U1'), array([['C', 'D'],
       ['G', 'H']], dtype='<U1')]
