# Q1: Import numpy library

In [170]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [171]:
seq = np.linspace(1,5, 15, dtype = float)
seq

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [172]:
arr1 = np.arange(1.1, 4.1, dtype= float)
arr2 = np.arange(4.1, 7.1, dtype= float)
arr3 = np.arange(7.1, 10.1, dtype= float)
arr4 = np.arange(10.1, 13.1, dtype= float)

newArray = np.concatenate((arr1, arr2, arr3, arr4), axis= None).reshape(2,2,3)
newArray

array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [173]:
print(f'{newArray.ndim},{newArray.dtype},{newArray.shape},{newArray.size},{type(newArray)}')

3,float64,(2, 2, 3),12,<class 'numpy.ndarray'>


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [174]:
nwArr = newArray.reshape(len(newArray),2,3,1)
print(f'{nwArr.ndim},{nwArr.shape}')

4,(2, 2, 3, 1)


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [175]:
nwArr = nwArr.astype('int')
nwArr.dtype

dtype('int64')

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [176]:
print(nwArr)
for i in np.nditer(nwArr):
    print(i)

[[[[ 1]
   [ 2]
   [ 3]]

  [[ 4]
   [ 5]
   [ 6]]]


 [[[ 7]
   [ 8]
   [ 9]]

  [[10]
   [11]
   [12]]]]
1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [177]:
nwArr[1,0][1:2]

array([[8]])

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [178]:
nwArr[0,1][1:3]

array([[5],
       [6]])

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [179]:
a = np.where(nwArr == 8)
a

(array([1]), array([0]), array([1]), array([0]))

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [180]:
nwArr.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [181]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

array = np.stack((arr1, arr2))
array

array([[['A', 'B'],
        ['E', 'F']],

       [['C', 'D'],
        ['G', 'H']]], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [182]:
np.stack((arr1, arr2), axis = 1)

array([[['A', 'B'],
        ['C', 'D']],

       [['E', 'F'],
        ['G', 'H']]], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [232]:
arr1,arr2=np.split(array,2,axis=1)
arr1 = np.array_split(arr1.flatten(),4)
arr2 = np.array_split(arr2.flatten(),4)

print(arr1,arr2)

[array(['A'], dtype='<U1'), array(['B'], dtype='<U1'), array(['C'], dtype='<U1'), array(['D'], dtype='<U1')] [array(['E'], dtype='<U1'), array(['F'], dtype='<U1'), array(['G'], dtype='<U1'), array(['H'], dtype='<U1')]
